blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

djangoproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)

    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            self.excerpt = self.body[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_time']


class UploadModel(models.Model):
    # 文件被传至`MEDIA_ROOT/uploads`目录，MEDIA_ROOT由你在settings文件中设置
    # upload = models.FileField(upload_to='uploads/')
    # 或者
    # 被传到`MEDIA_ROOT/uploads/2015/01/30`目录，增加了一个时间划分
    upload = models.FileField(upload_to='uploads/%Y/%m/%d/')

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


# Create your models here.

@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

comments/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

blog/views.py
import django.shortcuts
# Create your views here.
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
from comments.forms import CommentForm
from django.views.generic import ListView


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm()
    comment_list = post.comment_set.all()
    post.increase_views()

    context = {
        'post': post,
        'form': form,
        'comment_list': comment_list
    }
    return render(request, 'blog/detail.html', context=context)


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
    return render(request, 'blog/index.html', context={'post_list': post_list})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)

    return render(request, 'blog/index.html', context={'post_list': post_list})

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post

# from .models import Comment
from .forms import CommentForm


def post_comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    # 这里我们使用了 Django 提供的一个快捷函数 get_object_or_404，
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户。
    post = get_object_or_404(Post, pk=post_pk)

    # HTTP 请求有 get 和 post 两种，一般用户通过表单提交数据都是通过 post 请求，
    # 因此只有当用户的请求为 post 时才需要处理表单数据。
    if request.method == 'POST':
        # 用户提交的数据存在 request.POST 中，这是一个类字典对象。
        # 我们利用这些数据构造了 CommentForm 的实例，这样 Django 的表单就生成了。
        form = CommentForm(request.POST)

        # 当调用 form.is_valid() 方法时，Django 自动帮我们检查表单的数据是否符合格式要求。
        if form.is_valid():
            # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
            comment = form.save(commit=False)

            # 将评论和被评论的文章关联起来。
            comment.post = post

            # 最终将评论数据保存进数据库，调用模型实例的 save 方法
            comment.save()

            # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
            # 然后重定向到 get_absolute_url 方法返回的 URL。
            return redirect(post)

        else:
            # 检查到数据不合法，重新渲染详情页，并且渲染表单的错误。
            # 因此我们传了三个模板变量给 detail.html，
            # 一个是文章（Post），一个是评论列表，一个是表单 form
            # 注意这里我们用到了 post.comment_set.all() 方法，
            # 这个用法有点类似于 Post.objects.all()
            # 其作用是获取这篇 post 下的的全部评论，
            # 因为 Post 和 Comment 是 ForeignKey 关联的，
            # 因此使用 post.comment_set.all() 反向查询全部评论。
            # 具体请看下面的讲解。
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'blog/detail.html', context=context)
    # 不是 post 请求，说明用户没有提交数据，重定向到文章详情页。
    return redirect(post)

blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <title>李鹏程的网络日志</title>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/base-min.css">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
</head>

<body>
<div class="wrap">
    <header class="com-header">
        <div class="header-name">
            <a href="{% url 'blog:index' %}">李鹏程的网络日志</a>
        </div>
        <div class="header-search">
            <input type="search" placeholder="搜索" required>
            <button type="submit">搜索</button>
        </div>
    </header>
    <main class="com-main">
        <div class="main-body">
            {% block main %}
            {% endblock main %}
        </div>
        {% block sidebar %}
        {% endblock sidebar %}
    </main>
    <footer class="com-footer"></footer>
</div>


</body>

</html>

blog/templates/blog/archives.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <h1 class="post-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="post-meta">
                <span class="post-date">{{ post.created_time }}</span>
                <span class="views-count">阅读({{ post.views }})</span>
            </div>
            <div class="post-excerpt">{{ post.excerpt }}</div>
            <div class="read-more">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读→ </a>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock main %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="post-title">{{ post.title }}</h1>
            <div class="post-meta">
                <span class="post-date">{{ post.created_time }}</span>
                <span class="post-author">{{ post.author }}</span>
                <span class="comments-link">4 评论</span>
                <span class="views-count">阅读(588)</span>
            </div>
        </header>
        <div class="post-content clearfix">
            {{ post.body }}
        </div>
    </article>
    <section class="comment" id="comment-area">
        <h3 class="comment-title">发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="form-row">
                <label for="{{ form.name.id_for_label }}">名字：</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="form-row">
                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="form-row">
                <label for="{{ form.url.id_for_label }}">URL：</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            <div class="form-row comment-content">
                <label for="{{ form.text.id_for_label }}">评论：</label>
                {{ form.text }}
                {{ form.text.errors }}
            </div>
            <div class="form-row">
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </form>
        <div class="comment-list-panel">
            <h3 class="comment-title">评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <span class="submit-date">{{ comment.created_time }}</span>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <h1 class="post-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="post-meta">
                <span class="post-date">{{ post.created_time }}</span>
                <span class="views-count">阅读({{ post.views }})</span>
            </div>
            <div class="post-excerpt">{{ post.excerpt }}</div>
            <div class="read-more">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读→ </a>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock main %}


{% block sidebar %}
<div class="main-sidebar">
    <div class="widget recent-posts">
        <h3 class="title">最新文章</h3>
        {% get_recent_posts as recent_post_list %}
        <ul class="content">
            {% for post in recent_post_list %}
                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
            {% empty %}
                暂无文章
            {% endfor %}
        </ul>
    </div>
    <div class="widget archives">
        <h3 class="title">归档</h3>
        {% archives as date_list %}
        <ul class="content">
            {% for date in date_list %}
                <li>
                    <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a>
                </li>
            {% empty %}
                暂无归档
            {% endfor %}
        </ul>
    </div>

    <div class="widget category">
        <h3 class="title">分类</h3>
        {% get_categories as categories %}
        <ul class="content">
            {% for cate in categories %}
                <li>
                    <a href="{% url 'blog:category' cate.pk %}">{{ cate.name }}<span
                            class="post-count">(13)</span></a>
                </li>
            {% empty %}
                暂无分类
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock sidebar %}